//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_manager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GongZuoXinXi
    {
        public int id { get; set; }
        public string zhaopinbiaoti { get; set; }
        public string zhaoPinZheLeiXingid { get; set; }
        public string gongZuoLeiXing { get; set; }
        public string sex { get; set; }
        public string zhouMoJianZhi { get; set; }
        public string xinChouShuLiang { get; set; }
        public string zhaoPinRenShu { get; set; }
        public string kaiShiShiJian { get; set; }
        public string jieZhiShiJian { get; set; }
        public string chengShiQuYu { get; set; }
        public string gongZuoDiZhi { get; set; }
        public string xiangQing { get; set; }
        public string lianXiFangShi { get; set; }
        public Nullable<System.DateTime> faBuShiJian { get; set; }
        public Nullable<int> yingPinXueShengid { get; set; }
        public string yingPinQingKuang { get; set; }
        public Nullable<int> luYongXueShengid { get; set; }
        public string luYongQingKuang { get; set; }
        public string yunXuFaBu { get; set; }
        public string zhaoMan { get; set; }
    }
}
