//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_manager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XueShengXinXi
    {
        public int id { get; set; }
        public string name { get; set; }
        public byte[] head_image { get; set; }
        public string phone { get; set; }
        public string pass { get; set; }
        public string huiYuan { get; set; }
        public string diZhi { get; set; }
        public Nullable<System.DateTime> chuShengRiQi { get; set; }
        public string nianJi { get; set; }
        public string shouCangShangJia { get; set; }
        public string shouCangGongZuo { get; set; }
        public Nullable<int> ciShu { get; set; }
        public Nullable<int> xinYong { get; set; }
        public string shangJia { get; set; }
        public Nullable<int> zhaoPinZheid { get; set; }
        public string qq { get; set; }
        public string weixin { get; set; }
        public Nullable<System.DateTime> day_login { get; set; }
    }
}
