//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_manager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XueShengQiuZhi
    {
        public int id { get; set; }
        public int gongZuoLeiXingid { get; set; }
        public string name { get; set; }
        public string titie { get; set; }
        public string xinXi { get; set; }
        public System.DateTime faBuShiJian { get; set; }
        public int xueShengid { get; set; }
        public int shangJiaid { get; set; }
        public string zhongyishangjia { get; set; }
        public string xuanze商家 { get; set; }
        public Nullable<System.DateTime> chengLiShiJian { get; set; }
    }
}
