//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_manager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XueShengJiaoYiJiLu
    {
        public int id { get; set; }
        public string name { get; set; }
        public int xueShengid { get; set; }
        public string jiLu { get; set; }
        public string wanCheng { get; set; }
        public string pingJia { get; set; }
        public Nullable<System.DateTime> wanChengJiaoYiShiJian { get; set; }
        public string keJian { get; set; }
    }
}
