//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_manager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XueShengKeCheng
    {
        public int id { get; set; }
        public string name { get; set; }
        public int xueshengid { get; set; }
        public string xuexiao { get; set; }
        public string xuehao { get; set; }
        public string xuehaopass { get; set; }
        public string yi { get; set; }
        public string er { get; set; }
        public string san { get; set; }
        public string si { get; set; }
        public string wu { get; set; }
        public string liu { get; set; }
        public string qi { get; set; }
    }
}
